### ISSUE TITLE
some note !!

### ISSUE THREAD

**Issue by sajjjadayobi** [m3hrdadfi/albert-persian#2]
hi Merhdad, thank you for your great job,
you don't have any TF-model in your model card 
as you can't see here https://huggingface.co/m3hrdadfi/albert-fa-base-v2/tree/main

and another point, 
as you know that for working with Albert we need to install the sentence piece library
but I think it's would be great if you mention it in the readme file
 (in the first use I didn't know that maybe there are some people like me)

**Comment by m3hrdadfi** [comment]
@sajjjadayobi Thank you for your interest.

I didn't have the time to convert the torch version to TF one, but I'll do it shortly, I suppose 😉 . You can add this forgotten package into the `How to use` section and send your PR ASAP.

**Comment by sajjjadayobi** [comment]
ok, I sent it to you
