### ISSUE TITLE
request for contribution (I wrote an Example for this repo)

### ISSUE THREAD

**Issue by sajjjadayobi** [m3hrdadfi/albert-persian#4]
Hi Mehrdad, I wrote an Example for Text Classification with Albert-Persian on Colab
Colab link: https://colab.research.google.com/drive/1ICmlf0zLiomtsFsCkkQny_HJN6X2w_of?usp=sharing
it's like your Taaghche_Sentiment_Analysis on ParsBert
I trained it both on TF 2.0 and PyTorch

it's almost done
it just needs some comments and notations for how to use 

please check it, and if is this ok?
accept my PR for adding this on the notebooks folder and examples on the Readme File

note: I didn't send the PR yet

**Comment by m3hrdadfi** [comment]
Hi @sajjjadayobi, 

Thanks for your contribution, but your notebook doesn't available publicly!
So, I couldn't check that.

**Comment by sajjjadayobi** [comment]
I'm sorry, I forgot to convert it into shareable
new link:https://colab.research.google.com/drive/1ICmlf0zLiomtsFsCkkQny_HJN6X2w_of?usp=sharing
please check this out
