### ISSUE TITLE
use for different entity

### ISSUE THREAD

**Issue by ds-sabmlt** [m3hrdadfi/albert-persian#6]
Hi
Is it possible to The fine-tuned this model on my dataset that have different entities? 
thanks

**Comment by m3hrdadfi** [comment]
Hi @ds-sabmlt,

Yes, it's possible. You can fine-tune all the existing versions ([v1](https://huggingface.co/m3hrdadfi/albert-fa-base-v2), [v2](https://huggingface.co/HooshvareLab/albert-fa-zwnj-base-v2)) on your own data.

* As a suggestion, I prefer version 2. It supports all types of Persian characters as well as zero-width non-joiner.
